import urllib.parse
import re
import time
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from playwright.sync_api import sync_playwright

# ==================== 频道配置 (将按此顺序输出) ====================
CHANNELS = [
    ("cctv1",  "CCTV-1",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=11200132825562653886"),
    ("cctv2",  "CCTV-2",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=12030532124776958103"),
    ("cctv4",  "CCTV-4",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=10620168294224708952"),
    ("cctv7",  "CCTV-7",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=8516529981177953694"),
    ("cctv9",  "CCTV-9",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=7252237247689203957"),
    ("cctv10", "CCTV-10", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=14589146016461298119"),
    ("cctv12", "CCTV-12", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=13180385922471124325"),
    ("cctv13", "CCTV-13", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=16265686808730585228"),
    ("cctv17", "CCTV-17", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=4496917190172866934"),
    ("cctv4k", "CCTV-4K", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=2127841942201075403"),
]

lock = threading.Lock()

def safe_print(msg):
    with lock:
        print(msg)

# ==================== 核心抓取逻辑 ====================

def extract_channel(name, display_name, url, max_wait=30):
    captured_urls = set()
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36",
            viewport={"width": 360, "height": 661},
            is_mobile=True
        )
        page = context.new_page()

        def handle_request(request):
            if ".m3u8" in request.url:
                captured_urls.add(request.url)

        page.on("request", handle_request)
        try:
            page.goto(url, wait_until="domcontentloaded", timeout=30000)
            # 自动尝试播放
            for sel in ["button.custom-prism-play-control", "video", ".play-icon"]:
                try:
                    if page.is_visible(sel, timeout=3000):
                        page.click(sel)
                        break
                except: continue
            
            # 等待链接捕获
            start = time.time()
            while not captured_urls and (time.time() - start < max_wait):
                time.sleep(1)
        except Exception as e:
            safe_print(f"❌ [{display_name}] 错误: {e}")
        finally:
            browser.close()

    # 清理并去重
    refined = []
    for raw in captured_urls:
        clean = urllib.parse.unquote(raw)
        clean = re.sub(r'.*?(https://live-play-hls\.cctvnews\.cctv\.com.*?)(?:&stack.*)?$', r'\1', clean)
        if clean not in refined:
            refined.append(clean)

    safe_print(f"✅ [{display_name}] 捕获完成 ({len(refined)} 个源)")
    return name, display_name, refined

def generate_m3u(all_results, filename="cctv_live.m3u"):
    """生成文件"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write("#EXTM3U\n# Generated by CCTV Scraper\n\n")
        count = 0
        for name, display_name, urls in all_results:
            for url in urls:
                f.write(f'#EXTINF:-1 tvg-id="{name}" tvg-name="{display_name}" group-title="CCTV",{display_name}\n')
                f.write(f"{url}\n\n")
                count += 1
    print(f"\n🎉 文件生成成功！共 {count} 条线路已按顺序排列。")

# ==================== 执行入口 ====================

def main():
    # 1. 创建频道顺序索引字典，用于排序
    order_map = {item[0]: i for i, item in enumerate(CHANNELS)}
    
    final_data = []
    print(f"🚀 开始并发抓取 {len(CHANNELS)} 个频道...\n")

    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = {
            executor.submit(extract_channel, cid, cname, curl): cid 
            for cid, cname, curl in CHANNELS
        }
        
        for future in as_completed(futures):
            res = future.result()
            final_data.append(res)

    # 2. 核心：按照原始 CHANNELS 列表的顺序进行排序
    # x[0] 是频道 id (如 'cctv1')，通过 order_map 找到它在原始列表中的位置
    final_data.sort(key=lambda x: order_map.get(x[0], 999))

    # 3. 输出文件
    generate_m3u(final_data)

if __name__ == "__main__":
    main()
