import urllib.parse
import re
import time
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from playwright.sync_api import sync_playwright

# ==================== 频道配置 ====================
# 包含频道别名、显示名称和官方直播页地址
CHANNELS = [
    ("cctv1",  "CCTV-1",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=11200132825562653886"),
    ("cctv2",  "CCTV-2",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=12030532124776958103"),
    ("cctv4",  "CCTV-4",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=10620168294224708952"),
    ("cctv7",  "CCTV-7",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=8516529981177953694"),
    ("cctv9",  "CCTV-9",  "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=7252237247689203957"),
    ("cctv10", "CCTV-10", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=14589146016461298119"),
    ("cctv12", "CCTV-12", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=13180385922471124325"),
    ("cctv13", "CCTV-13", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=16265686808730585228"),
    ("cctv17", "CCTV-17", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=4496917190172866934"),
    ("cctv4k", "CCTV-4K", "https://m-live.cctvnews.cctv.com/live/landscape.html?liveRoomNumber=2127841942201075403"),
]

# 线程锁，确保控制台打印不乱序
lock = threading.Lock()

def safe_print(msg):
    with lock:
        print(msg)

# ==================== 核心逻辑 ====================

def extract_channel(name, display_name, url, max_wait=30):
    """
    使用 Playwright 模拟移动端访问并捕获所有 m3u8 请求
    """
    captured_urls = set()

    with sync_playwright() as p:
        # 启动浏览器 (无头模式)
        browser = p.chromium.launch(headless=True)
        # 模拟 Android 设备环境
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36",
            viewport={"width": 360, "height": 661},
            is_mobile=True
        )
        page = context.new_page()

        # 监听所有网络请求
        def handle_request(request):
            if ".m3u8" in request.url:
                captured_urls.add(request.url)

        page.on("request", handle_request)

        safe_print(f"[*] [{display_name}] 正在打开页面...")
        try:
            page.goto(url, wait_until="domcontentloaded", timeout=30000)
            
            # 尝试点击播放按钮以触发流媒体请求
            selectors = ["button.custom-prism-play-control", "#player button", "video", ".play-icon"]
            clicked = False
            for sel in selectors:
                try:
                    if page.is_visible(sel, timeout=5000):
                        page.click(sel)
                        safe_print(f"[*] [{display_name}] 点击播放成功")
                        clicked = True
                        break
                except:
                    continue
            
            if not clicked:
                # 强制 JS 播放
                page.evaluate("const v = document.querySelector('video'); if (v) v.play();")

            # 等待数据流出现
            start_time = time.time()
            while not captured_urls and (time.time() - start_time < max_wait):
                time.sleep(1)
                
        except Exception as e:
            safe_print(f"❌ [{display_name}] 加载异常: {e}")
        finally:
            browser.close()

    # URL 清理与去重
    refined_results = []
    for raw_url in captured_urls:
        # 解码并去除冗余参数（针对央视接口的正则清理）
        clean_url = urllib.parse.unquote(raw_url)
        clean_url = re.sub(r'.*?(https://live-play-hls\.cctvnews\.cctv\.com.*?)(?:&stack.*)?$', r'\1', clean_url)
        
        if clean_url not in refined_results:
            refined_results.append(clean_url)

    safe_print(f"✅ [{display_name}] 抓取完成，找到 {len(refined_results)} 个源")
    return name, display_name, refined_results


def generate_m3u(all_results, filename="cctv_live.m3u"):
    """
    生成 M3U 文件：同一频道的多个源共享相同的 ID 和名称
    """
    with open(filename, "w", encoding="utf-8") as f:
        f.write("#EXTM3U\n")
        f.write("# Generated by CCTV Multi-Source Scraper\n\n")

        total_lines = 0
        for name, display_name, urls in all_results:
            if not urls:
                continue
            
            for url in urls:
                # 写入标准 M3U 格式，tvg-id 和展示名保持一致
                f.write(f'#EXTINF:-1 tvg-id="{name}" tvg-name="{display_name}" group-title="CCTV",{display_name}\n')
                f.write(f"{url}\n\n")
                total_lines += 1

    print(f"\n" + "="*50)
    print(f"🚀 任务结束！")
    print(f"📁 文件已保存至: {filename}")
    print(f"📊 总计抓取频道: {len([x for x in all_results if x[2]])}")
    print(f"🔗 总计输出线路: {total_lines}")
    print("="*50)


def main():
    MAX_WORKERS = 4  # 并发数，建议不要设置太高以免被封或造成系统卡顿
    
    print(f"开始抓取央视直播源，预计并发线程数: {MAX_WORKERS}\n")
    
    final_data = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        # 提交所有任务
        task_map = {
            executor.submit(extract_channel, cid, cname, curl): cname 
            for cid, cname, curl in CHANNELS
        }
        
        # 收集结果
        for future in as_completed(task_map):
            try:
                res = future.result()
                final_data.append(res)
            except Exception as e:
                safe_print(f"❌ 线程池执行错误: {e}")

    # 排序（按原始列表顺序）
    final_data.sort(key=lambda x: [c[0] for c in CHANNELS].index(x[0]))
    
    # 生成文件
    generate_m3u(final_data)


if __name__ == "__main__":
    main()
